### ISSUE TITLE
Not php 8-compatible?

### ISSUE THREAD

**Issue by lfolco** [elgentos/laravel-coding-standards#3]
This is based on https://github.com/mediact/coding-standard, which is end of life and has a dependency on PHP 7. Any plans to update?

**Comment by celorodovalho** [comment]
+1

Please, update the dependencies to https://github.com/YouweGit/coding-standard @peterjaap 

#4

**Comment by peterjaap** [comment]
Thanks!

**Comment by celorodovalho** [comment]
@peterjaap can you please that the commit with a new version? 1.0.1?

**Comment by peterjaap** [comment]
Done! :)
